/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ToHtmlArgs {
  ugly?: boolean
}
export declare function bbcodeToHtml(input: string, args?: ToHtmlArgs | undefined | null): string
